version: '3.7'
networks:
    overlay:
        driver: bridge
services:
    php:
        container_name: docker-sample_php
        build: .docker/php-fpm
        volumes:
            - ./app:/var/www/html
            - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        networks:
            - overlay
    nginx:
        container_name: docker-sample_nginx
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
        networks:
            - overlay
    mysql:
        container_name: docker-sample_mysql
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3333:3306"
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - overlay
    redis:
        container_name: docker-sample_redis
        build: .docker/redis
        ports:
            - "6379:6379"